Auto-Detect the target server for failover

diff --git a/roles/httpd/files/failover-www b/roles/httpd/files/failover-www
--- a/roles/httpd/files/failover-www
+++ b/roles/httpd/files/failover-www
@@ -1,7 +1,5 @@
 #!/bin/sh
 
-TARGET=$1
-
 # {{{ switch_elb()
 
 switch_elb() {
@@ -26,15 +24,14 @@ if [ `id -u` != 0 ]; then
   exit 1
 fi
 
-if [ "$TARGET" == "1" ]; then
+if [ "`hostname -s`" == "charlie" ]; then
   src=2
   arn=arn:aws:elasticloadbalancing:ap-northeast-1:070392599442:targetgroup/www1-only/3c1cd41a0ad83b00
-elif [ "$TARGET" == "2" ]; then
+elif [ "`hostname -s`" == "foxtrot" ]; then
   src=1
   arn=arn:aws:elasticloadbalancing:ap-northeast-1:070392599442:targetgroup/www2-only/0883aaddf820f2b1
 else
-  echo "<USAGE> failover-www <target-number>" >&2
-  echo "        target-number: 1 or 2" >&2
+  echo "<USAGE> failover-www" >&2
   exit 1
 fi
 
diff --git a/roles/postfix/files/failover-mail b/roles/postfix/files/failover-mail
--- a/roles/postfix/files/failover-mail
+++ b/roles/postfix/files/failover-mail
@@ -1,6 +1,5 @@
 #!/bin/sh
 
-TARGET=$1
 JSONFILE=/tmp/upsert-mail-rewse-jp.json
 
 # {{{ switch_dns()
@@ -17,7 +16,7 @@ switch_dns() {
         "TTL": 300,
         "ResourceRecords": [
           {
-            "Value": "mail$TARGET.rewse.jp"
+            "Value": "mail$target.rewse.jp"
           }
         ]
       }
@@ -43,13 +42,14 @@ if [ `id -u` != 0 ]; then
   exit 1
 fi
 
-if [ "$TARGET" == "1" ]; then
+if [ "`hostname -s`" == "charlie" ]; then
   src=2
-elif [ "$TARGET" == "2" ]; then
+  target=1
+elif [ "`hostname -s`" == "foxtrot" ]; then
   src=1
+  target=2
 else
-  echo "<USAGE> failover-mail <target-number>" >&2
-  echo "        target-numuber: 1 or 2" >&2
+  echo "<USAGE> failover-mail" >&2
   exit 1
 fi
 
@@ -64,6 +64,7 @@ for i in `seq 1 20`; do
   sleep 1
   echo -n "."
 done
+echo ""
 
 echo "Stopping lsyncd on mail$src..."
 ssh centos@mail$src sudo systemctl stop lsyncd
diff --git a/roles/zabbix/server/files/failover-zabbix-server b/roles/zabbix/server/files/failover-zabbix-server
--- a/roles/zabbix/server/files/failover-zabbix-server
+++ b/roles/zabbix/server/files/failover-zabbix-server
@@ -1,6 +1,5 @@
 #!/bin/sh
 
-TARGET=$1
 JSONFILE=/tmp/upsert-zabbix-rewse-jp.json
 
 # {{{ switch_dns()
@@ -17,7 +16,7 @@ switch_dns() {
         "TTL": 300,
         "ResourceRecords": [
           {
-            "Value": "zabbix$TARGET.rewse.jp"
+            "Value": "zabbix$target.rewse.jp"
           }
         ]
       }
@@ -40,13 +39,14 @@ if [ `id -u` != 0 ]; then
   exit 1
 fi
 
-if [ "$TARGET" == "1" ]; then
+if [ "`hostname -s`" == "charlie" ]; then
   src=2
-elif [ "$TARGET" == "2" ]; then
+  target=1
+elif [ "`hostname -s`" == "foxtrot" ]; then
   src=1
+  target=2
 else
-  echo "<USAGE> failover-zabbix-server <target-number>" >&2
-  echo "        target-numuber: 1 or 2" >&2
+  echo "<USAGE> failover-zabbix-server" >&2
   exit 1
 fi
 
